### ISSUE TITLE
Celery cannot connect to rabbitmq

### ISSUE THREAD

**Issue by Eshaan7** [certego/IntelOwl#16]
**Issue I am facing:**
When I create a new analyze request using the [pyintelowl](https://github.com/mlodic/pyintelowl) client, the job gets created but it keeps saying `status: "running" and the command hangs, see here:

![](https://i.imgur.com/ZhZaYI3.png)

And if I visit the server's GUI to query the database, this is what I get:

![](https://i.imgur.com/FeGFFMc.png)

The job just hangs there finally throws me time-out error.

**What I tried:**

I have tried with different analyzers, different files and observables as well. I am facing the same issue. 
There are no errors in my docker-compose terminal.

Any help would be appreciated.

**Comment by Eshaan7** [comment]
Turns out, It was an issue with the `CELERY_BROKER_URL` environment variable. Instead of `CELERY_BROKER_URL=ampq://localhost`, it should be `CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672`.

I think that should be changed in the Dockerfile.

**Comment by mlodic** [comment]
Thank you!, merged your pull request
