### ISSUE TITLE
ThreatMiner API

### ISSUE THREAD

**Issue by amanjiofficial** [certego/IntelOwl#19]
We should add an analyzer to extract info about an IP/URL/hash from ThreatMiner.

https://www.threatminer.org/api.php

Suggestions Please @mlodic.

**Comment by mlodic** [comment]
Good idea. You could create a single ThreatMiner Analyzer module, then you could add multiple Analyzer Configurations to allow Intel Owl users to run every different query type available (whois rt=1,  passivedns rt=2, ...)
