### ISSUE TITLE
GreyNoise API Integration

### ISSUE THREAD

**Issue by Eshaan7** [certego/IntelOwl#33]
Stumbled upon [GreyNoise](https://viz.greynoise.io/). 
They have an "IP Context" API endpoint - https://docs.greynoise.io/#ip-context.

Should we integrate this ? @mlodic

**Comment by mlodic** [comment]
Greynoise is great but the API keys that they provide can be used only for 15-days. 

There is no "free" API key that you can use with a limited quota forever. That would be great for the community. :(

At the moment Intel Owl already contains an analyzer for the Greynoise Alpha free endpoint that does not require authentication. (https://github.com/GreyNoise-Intelligence/api.greynoise.io)

**Comment by Eshaan7** [comment]
I think we can integrate the analyzer. Afterall, it's upto the user/organization if they have a paid API key or not for GreyNoise's API.

**Comment by mlodic** [comment]
Yep we can do this

**Comment by mlodic** [comment]
Done in #52
