### ISSUE TITLE
OPSWAT Metadefender API

### ISSUE THREAD

**Issue by amanjiofficial** [certego/IntelOwl#37]
We should add an analyzer to extract info from opswat metadefender cloud

https://onlinehelp.opswat.com/mdcloud/Description_of_file_categories.html

Suggestions Please @mlodic

**Comment by mlodic** [comment]
If you check here [docs](https://onlinehelp.opswat.com/mdcloud/3._Public_APIs.html), they do not allow the usage or the saving of the generated data even for free API keys.
