### ISSUE TITLE
First Use Clarity

### ISSUE THREAD

**Issue by weslambert** [certego/IntelOwl#42]
It's not really clear on first use what analyzers are available, or how the platform is to be used.  For example, I try to search an MD5 once logged in (eg. Mimikatz) and get no results.  Do I need to enable some more analyzers, or is there something else I must do to populate a local DB?

**Comment by weslambert** [comment]
I realize there is the JSON config file for analyzers, but from a web perspective, it is a little unclear.

**Comment by mlodic** [comment]
Hi @weslambert, thank you for your interest.

I suggest you to go through the docs. https://intelowl.readthedocs.io/en/latest/
At the moment the interface is very minimal and the better way to use this project is to integrate it via API with other security tools, or using the official client manually (https://github.com/mlodic/pyintelowl).
The single page available from the interface allows the user to look for already launched jobs, nothing more. So it is normal that you did not find anything.

However we are planning to create a fresh new interface for the project (see #13) to allow users to interact with Intel Owl manually more easily.

**Comment by weslambert** [comment]
Thanks, that helps to clarify a good deal.  I was already planning on using the Python client, as I would like to call the API from another tool, but just wanted to test locally before doing so.  I'll proceed with the client/API, and let you know if I have any issues.  Thanks for the quick response!
