### ISSUE TITLE
URLhaus integration

### ISSUE THREAD

**Issue by mlodic** [certego/IntelOwl#55]
https://urlhaus-api.abuse.ch

Check a URL, domain or IP against the URLhaus database

**Comment by Eshaan7** [comment]
Can also check for Hash (md5/sha256 hash of malware sample), as described [here](https://urlhaus-api.abuse.ch/#payloadinfo)

**Comment by mlodic** [comment]
Yes but I think that those files are the same of the "MalwareBazaar" API you already implemented, so I would not care of this endpoint.

**Comment by mlodic** [comment]
Solved
